{
  super("An exception occurred in a callback",root);
}
